name: dynamic_gaussians
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - gradio
  - hydra-core
  - einops
  - scipy
  - trimesh
  - tensorboard
  - pyglet<2
  - matplotlib
  - python=3.10
  - pip=22.3.1
  - pytorch
  - pytorch-cuda
  - torchaudio
  - torchvision
  - tqdm=4.65.0
  - Pillow=9.4.0
  - pip:
    - open3d==0.16.0
    - huggingface-hub[torch]>=0.22
    - roma
    - opencv-python